- name: Ensure OpenSSH server is installed
  ansible.builtin.apt:
    name: openssh-server
    state: present

- name: Ensure nginx is running and enabled
  ansible.builtin.service:
    name: ssh
    state: started
    enabled: true

- name: Apply SSH hardening settings
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^{{ item.key }} "
    line: "{{ item.key }} {{ item.value }}"
    state: present
    backup: yes
  loop: "{{ ssh_config | dict2items }}"
  notify: Restart ssh

- name: Allow SSH through UFW
  community.general.ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: Ensure Fail2ban is installed
  ansible.builtin.apt:
    name:
      - fail2ban
    state: present

- name: Ensure Fail2ban is running and enabled
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true