- name: Ensure users exist
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: "{{ item.groups | default('') }}"
    append: yes
    shell: /bin/bash
    state: present
    create_home: yes
  loop: "{{ users }}"

- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "/home/{{ item.name }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  loop: "{{ users }}"

- name: Set authorized keys
  ansible.builtin.authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.pubkey }}"
  loop: "{{ users }}"
  when: item.pubkey is defined
