- name: Show host group info
  hosts: jellyfin
  connection: local
  gather_facts: yes
  tasks:
    - debug:
        msg:
          hostname: "{{ inventory_hostname }}"
          groups: "{{ group_names }}"
          # all_vars: "{{ hostvars[inventory_hostname] }}"

- name: The Jellyfin Media Servers
  hosts: jellyfin
  connection: local
  become: yes
  roles:
    - common
    - users
    - ssh
    - jellyfin
